steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/poke-mart-007919/poke-mart", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/poke-mart-007919/poke-mart"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "poke-mart"
      - "--image"
      - "gcr.io/poke-mart-007919/poke-mart"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"

options:
  logging: "CLOUD_LOGGING_ONLY"
