steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/poke-mart-007919/poke-mart", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/poke-mart-007919/poke-mart"]
