export const trainers = [
  {
    city: "Pallet Town",
    email: "Ash@pikachu.com",
    firstname: "Ash",
    housenumber: "01",
    lastname: "Satoshi",
    password: "Pikachu1@",
    street: "PalletStreet",
    telephone: "151",
    zipcode: "151",
  },
  {
    city: "Pewter City",
    email: "Brock@onix.com",
    firstname: "Brock",
    housenumber: "10",
    lastname: "Takeshi ",
    password: "Geodude1@",
    street: "PewterGymStreet",
    telephone: "152",
    zipcode: "152",
  },
  {
    city: "Cerulean City",
    email: "Misty@starmie.com",
    firstname: "Misty",
    housenumber: "20",
    lastname: "Kasumi",
    password: "Starmie1@",
    street: "CeruleanGymStreet",
    telephone: "153",
    zipcode: "153",
  },
];
